package main

import (
	"first_task/go-fiber-api/internal/db"
	"first_task/go-fiber-api/internal/handlers"
	"first_task/go-fiber-api/internal/models"
	repo "first_task/go-fiber-api/internal/repository"
	"first_task/go-fiber-api/internal/services"

	_ "first_task/go-fiber-api/docs" // docs is generated by swag

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

// main.go should primarily:

//init the database.

//migrate using Gorm

//dependency injection of services, repos and handlers

//set up Fiber routes.

// start the Fiber server.
// @title Bookstore API
// @version 1.0
// @description This is a sample API for a bookstore.
// @host localhost:3000
// @BasePath /api
func main() {
	database, err := db.InitDB()
	if err != nil {
		panic("Failed to connect to database")
	}
	database.AutoMigrate(&models.Book{}, &models.User{})

	bookRepo := &repo.BookRepo{DB: database}
	userRepo := &repo.UserRepo{DB: database}

	bookService := services.NewBookService(bookRepo)
	userService := services.NewUserService(userRepo)

	bookHandler := handlers.NewBookHandler(bookService)
	userHandler := handlers.NewUserHandler(userService)

	app := fiber.New(fiber.Config{
		AppName: "MyFiberApp",
	})
	app.Use(logger.New())
	api := app.Group("/api")

	app.Get("/health", func(c *fiber.Ctx) error {
		return c.SendString("ok")
	})

	app.Get("/swagger/*", fiberSwagger.WrapHandler)
	books := api.Group("/books")
	books.Post("/", bookHandler.CreateBook)
	books.Get("/", bookHandler.GetAllBooks)
	books.Get("/:id", bookHandler.GetBookByID)
	books.Post("/:id/checkin", bookHandler.Checkin)
	books.Post("/:id/checkout", bookHandler.Checkout)

	users := api.Group("/users")
	users.Post("/", userHandler.CreateUser)
	users.Get("/", userHandler.GetAllUsers)
	users.Get("/:id", userHandler.GetUserByID)
	users.Put("/:id", userHandler.UpdateUser)

	// 8️⃣ Start server
	app.Listen(":3000")
}
